//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetDataViaWebServices.UnsignedUserName {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice", ConfigurationName="UnsignedUserName.IWSTrust13Sync")]
    public interface IWSTrust13Sync {
        
        // CODEGEN: Generating message contract since the operation Trust13Cancel is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Cancel", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RSTR/CancelFinal")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetDataViaWebServices.UnsignedUserName.Trust13CancelResponse Trust13Cancel(GetDataViaWebServices.UnsignedUserName.Trust13CancelRequest request);
        
        // CODEGEN: Generating message contract since the operation Trust13Issue is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RSTRC/IssueFinal")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetDataViaWebServices.UnsignedUserName.Trust13IssueResponse Trust13Issue(GetDataViaWebServices.UnsignedUserName.Trust13IssueRequest request);
        
        // CODEGEN: Generating message contract since the operation Trust13Renew is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Renew", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RSTR/RenewFinal")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetDataViaWebServices.UnsignedUserName.Trust13RenewResponse Trust13Renew(GetDataViaWebServices.UnsignedUserName.Trust13RenewRequest request);
        
        // CODEGEN: Generating message contract since the operation Trust13Validate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Validate", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RSTR/ValidateFinal")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetDataViaWebServices.UnsignedUserName.Trust13ValidateResponse Trust13Validate(GetDataViaWebServices.UnsignedUserName.Trust13ValidateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512")]
    public partial class RequestSecurityTokenType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] itemsField;
        
        private string contextField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512")]
    public partial class RequestSecurityTokenResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] itemsField;
        
        private string contextField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512")]
    public partial class RequestSecurityTokenResponseCollectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestSecurityTokenResponseType[] requestSecurityTokenResponseField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestSecurityTokenResponse", Order=0)]
        public RequestSecurityTokenResponseType[] RequestSecurityTokenResponse {
            get {
                return this.requestSecurityTokenResponseField;
            }
            set {
                this.requestSecurityTokenResponseField = value;
                this.RaisePropertyChanged("RequestSecurityTokenResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13CancelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken;
        
        public Trust13CancelRequest() {
        }
        
        public Trust13CancelRequest(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken) {
            this.RequestSecurityToken = RequestSecurityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13CancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection;
        
        public Trust13CancelResponse() {
        }
        
        public Trust13CancelResponse(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection) {
            this.RequestSecurityTokenResponseCollection = RequestSecurityTokenResponseCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13IssueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken;
        
        public Trust13IssueRequest() {
        }
        
        public Trust13IssueRequest(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken) {
            this.RequestSecurityToken = RequestSecurityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13IssueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection;
        
        public Trust13IssueResponse() {
        }
        
        public Trust13IssueResponse(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection) {
            this.RequestSecurityTokenResponseCollection = RequestSecurityTokenResponseCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13RenewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken;
        
        public Trust13RenewRequest() {
        }
        
        public Trust13RenewRequest(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken) {
            this.RequestSecurityToken = RequestSecurityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13RenewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection;
        
        public Trust13RenewResponse() {
        }
        
        public Trust13RenewResponse(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection) {
            this.RequestSecurityTokenResponseCollection = RequestSecurityTokenResponseCollection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken;
        
        public Trust13ValidateRequest() {
        }
        
        public Trust13ValidateRequest(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken) {
            this.RequestSecurityToken = RequestSecurityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trust13ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512", Order=0)]
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection;
        
        public Trust13ValidateResponse() {
        }
        
        public Trust13ValidateResponse(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection) {
            this.RequestSecurityTokenResponseCollection = RequestSecurityTokenResponseCollection;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTrust13SyncChannel : GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTrust13SyncClient : System.ServiceModel.ClientBase<GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync>, GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync {
        
        public WSTrust13SyncClient() {
        }
        
        public WSTrust13SyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTrust13SyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTrust13SyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTrust13SyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDataViaWebServices.UnsignedUserName.Trust13CancelResponse GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync.Trust13Cancel(GetDataViaWebServices.UnsignedUserName.Trust13CancelRequest request) {
            return base.Channel.Trust13Cancel(request);
        }
        
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType Trust13Cancel(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken) {
            GetDataViaWebServices.UnsignedUserName.Trust13CancelRequest inValue = new GetDataViaWebServices.UnsignedUserName.Trust13CancelRequest();
            inValue.RequestSecurityToken = RequestSecurityToken;
            GetDataViaWebServices.UnsignedUserName.Trust13CancelResponse retVal = ((GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync)(this)).Trust13Cancel(inValue);
            return retVal.RequestSecurityTokenResponseCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDataViaWebServices.UnsignedUserName.Trust13IssueResponse GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync.Trust13Issue(GetDataViaWebServices.UnsignedUserName.Trust13IssueRequest request) {
            return base.Channel.Trust13Issue(request);
        }
        
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType Trust13Issue(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken) {
            GetDataViaWebServices.UnsignedUserName.Trust13IssueRequest inValue = new GetDataViaWebServices.UnsignedUserName.Trust13IssueRequest();
            inValue.RequestSecurityToken = RequestSecurityToken;
            GetDataViaWebServices.UnsignedUserName.Trust13IssueResponse retVal = ((GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync)(this)).Trust13Issue(inValue);
            return retVal.RequestSecurityTokenResponseCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDataViaWebServices.UnsignedUserName.Trust13RenewResponse GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync.Trust13Renew(GetDataViaWebServices.UnsignedUserName.Trust13RenewRequest request) {
            return base.Channel.Trust13Renew(request);
        }
        
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType Trust13Renew(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken) {
            GetDataViaWebServices.UnsignedUserName.Trust13RenewRequest inValue = new GetDataViaWebServices.UnsignedUserName.Trust13RenewRequest();
            inValue.RequestSecurityToken = RequestSecurityToken;
            GetDataViaWebServices.UnsignedUserName.Trust13RenewResponse retVal = ((GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync)(this)).Trust13Renew(inValue);
            return retVal.RequestSecurityTokenResponseCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetDataViaWebServices.UnsignedUserName.Trust13ValidateResponse GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync.Trust13Validate(GetDataViaWebServices.UnsignedUserName.Trust13ValidateRequest request) {
            return base.Channel.Trust13Validate(request);
        }
        
        public GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenResponseCollectionType Trust13Validate(GetDataViaWebServices.UnsignedUserName.RequestSecurityTokenType RequestSecurityToken) {
            GetDataViaWebServices.UnsignedUserName.Trust13ValidateRequest inValue = new GetDataViaWebServices.UnsignedUserName.Trust13ValidateRequest();
            inValue.RequestSecurityToken = RequestSecurityToken;
            GetDataViaWebServices.UnsignedUserName.Trust13ValidateResponse retVal = ((GetDataViaWebServices.UnsignedUserName.IWSTrust13Sync)(this)).Trust13Validate(inValue);
            return retVal.RequestSecurityTokenResponseCollection;
        }
    }
}
