//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class TestDefaults : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestDefaults defaultInstance = ((TestDefaults)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestDefaults())));
        
        public static TestDefaults Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:59")]
        public global::System.TimeSpan TimeOut {
            get {
                return ((global::System.TimeSpan)(this["TimeOut"]));
            }
            set {
                this["TimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grosg1@capita.co.uk")]
        public string HeadTeacher {
            get {
                return ((string)(this["HeadTeacher"]));
            }
            set {
                this["HeadTeacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd")]
        public string HeadTeacherPassword {
            get {
                return ((string)(this["HeadTeacherPassword"]));
            }
            set {
                this["HeadTeacherPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SystemManager@capita.co.uk")]
        public string SystemManger {
            get {
                return ((string)(this["SystemManger"]));
            }
            set {
                this["SystemManger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string SystemMangerPassword {
            get {
                return ((string)(this["SystemMangerPassword"]));
            }
            set {
                this["SystemMangerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchoolAdmin@capita.co.uk")]
        public string SchoolAdministrator {
            get {
                return ((string)(this["SchoolAdministrator"]));
            }
            set {
                this["SchoolAdministrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string SchoolAdministratorPassword {
            get {
                return ((string)(this["SchoolAdministratorPassword"]));
            }
            set {
                this["SchoolAdministratorPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AssessCoord@capita.co.uk")]
        public string AssessmentCoordinator {
            get {
                return ((string)(this["AssessmentCoordinator"]));
            }
            set {
                this["AssessmentCoordinator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string AssessmentCoordinatorPassword {
            get {
                return ((string)(this["AssessmentCoordinatorPassword"]));
            }
            set {
                this["AssessmentCoordinatorPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CurrManager@capita.co.uk")]
        public string CurricularManager {
            get {
                return ((string)(this["CurricularManager"]));
            }
            set {
                this["CurricularManager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string CurricularManagerPassword {
            get {
                return ((string)(this["CurricularManagerPassword"]));
            }
            set {
                this["CurricularManagerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SeniorManager@capita.co.uk")]
        public string SeniorManagementTeam {
            get {
                return ((string)(this["SeniorManagementTeam"]));
            }
            set {
                this["SeniorManagementTeam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string SeniorManagementTeamPassword {
            get {
                return ((string)(this["SeniorManagementTeamPassword"]));
            }
            set {
                this["SeniorManagementTeamPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SENCoord@capita.co.uk")]
        public string SENCoordinator {
            get {
                return ((string)(this["SENCoordinator"]));
            }
            set {
                this["SENCoordinator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string SENCoordinatorPassword {
            get {
                return ((string)(this["SENCoordinatorPassword"]));
            }
            set {
                this["SENCoordinatorPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Personnel@capita.co.uk")]
        public string PersonnelOfficer {
            get {
                return ((string)(this["PersonnelOfficer"]));
            }
            set {
                this["PersonnelOfficer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string PersonnelOfficerPassword {
            get {
                return ((string)(this["PersonnelOfficerPassword"]));
            }
            set {
                this["PersonnelOfficerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teacher@capita.co.uk")]
        public string ClassTeacher {
            get {
                return ((string)(this["ClassTeacher"]));
            }
            set {
                this["ClassTeacher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string ClassTeacherPassword {
            get {
                return ((string)(this["ClassTeacherPassword"]));
            }
            set {
                this["ClassTeacherPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admissions@capita.co.uk")]
        public string AdmissionsOfficer {
            get {
                return ((string)(this["AdmissionsOfficer"]));
            }
            set {
                this["AdmissionsOfficer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string AdmissionsOfficerPassword {
            get {
                return ((string)(this["AdmissionsOfficerPassword"]));
            }
            set {
                this["AdmissionsOfficerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Returns@capita.co.uk")]
        public string ReturnsManager {
            get {
                return ((string)(this["ReturnsManager"]));
            }
            set {
                this["ReturnsManager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd01.")]
        public string ReturnsManagerPassword {
            get {
                return ((string)(this["ReturnsManagerPassword"]));
            }
            set {
                this["ReturnsManagerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan TimeOutDebug {
            get {
                return ((global::System.TimeSpan)(this["TimeOutDebug"]));
            }
            set {
                this["TimeOutDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iSIMSApplicationServerFarm1/DataEntityIO.svc/Transport")]
        public string ApplicationServerPath {
            get {
                return ((string)(this["ApplicationServerPath"]));
            }
            set {
                this["ApplicationServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iSIMSAuthorisationServerFarm1/iSIMSSTS.UnsignedUserName.svc")]
        public string SecurityServerPath {
            get {
                return ((string)(this["SecurityServerPath"]));
            }
            set {
                this["SecurityServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testuser@capita.co.uk")]
        public string TestUser {
            get {
                return ((string)(this["TestUser"]));
            }
            set {
                this["TestUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd")]
        public string TestUserPassword {
            get {
                return ((string)(this["TestUserPassword"]));
            }
            set {
                this["TestUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iSIMSMVCClientFarm1")]
        public string Path {
            get {
                return ((string)(this["Path"]));
            }
            set {
                this["Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchoolAdmin@capita.co.uk")]
        public string SchoolAdministratorUser {
            get {
                return ((string)(this["SchoolAdministratorUser"]));
            }
            set {
                this["SchoolAdministratorUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Personnel@capita.co.uk")]
        public string PersonnelOfficerUser {
            get {
                return ((string)(this["PersonnelOfficerUser"]));
            }
            set {
                this["PersonnelOfficerUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72262E2D-B292-E511-B386-000C29A7BA92")]
        public string SchoolID {
            get {
                return ((string)(this["SchoolID"]));
            }
            set {
                this["SchoolID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testuser@capita.co.uk")]
        public string User {
            get {
                return ((string)(this["User"]));
            }
            set {
                this["User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:04:30")]
        public global::System.TimeSpan AjaxElementTimeOut {
            get {
                return ((global::System.TimeSpan)(this["AjaxElementTimeOut"]));
            }
            set {
                this["AjaxElementTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int ObjectTimeOut {
            get {
                return ((int)(this["ObjectTimeOut"]));
            }
            set {
                this["ObjectTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:05")]
        public global::System.TimeSpan WaitLoading {
            get {
                return ((global::System.TimeSpan)(this["WaitLoading"]));
            }
            set {
                this["WaitLoading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Resource\\avatar.png")]
        public string PathAvatar {
            get {
                return ((string)(this["PathAvatar"]));
            }
            set {
                this["PathAvatar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Resource\\document.txt")]
        public string PathDocument {
            get {
                return ((string)(this["PathDocument"]));
            }
            set {
                this["PathDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan ElementTimeOut {
            get {
                return ((global::System.TimeSpan)(this["ElementTimeOut"]));
            }
            set {
                this["ElementTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lab-five.sims8.com/")]
        public string LabFiveURL {
            get {
                return ((string)(this["LabFiveURL"]));
            }
            set {
                this["LabFiveURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=lab-five.sims8.com;Initial Catalog=SIMS8_Farm1_Business_A;User ID=sa;" +
            "Password=Pa$$w0rd")]
        public string LabFiveDatabaseConnectionString {
            get {
                return ((string)(this["LabFiveDatabaseConnectionString"]));
            }
            set {
                this["LabFiveDatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lab-sims8.sims8.com/")]
        public string LabSims8URL {
            get {
                return ((string)(this["LabSims8URL"]));
            }
            set {
                this["LabSims8URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=lab-sims8.sims8.com;Initial Catalog=SIMS8_Farm1_Business_A;User ID=sa" +
            ";Password=Pa$$w0rd")]
        public string LabSims8DatabaseConnectionString {
            get {
                return ((string)(this["LabSims8DatabaseConnectionString"]));
            }
            set {
                this["LabSims8DatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=lab-two.sims8.com;Initial Catalog=SIMS8_Farm1_Business_A;User ID=sa;P" +
            "assword=Pa$$w0rd")]
        public string DatabaseConnectionString {
            get {
                return ((string)(this["DatabaseConnectionString"]));
            }
            set {
                this["DatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string SeleniumAutoStart {
            get {
                return ((string)(this["SeleniumAutoStart"]));
            }
            set {
                this["SeleniumAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Proxy {
            get {
                return ((string)(this["Proxy"]));
            }
            set {
                this["Proxy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lab-five")]
        public string DefaultSystemUnderTest {
            get {
                return ((string)(this["DefaultSystemUnderTest"]));
            }
            set {
                this["DefaultSystemUnderTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:04:00")]
        public global::System.TimeSpan BrowserResponseTimeout {
            get {
                return ((global::System.TimeSpan)(this["BrowserResponseTimeout"]));
            }
            set {
                this["BrowserResponseTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Water\'s Edge Primary School")]
        public string SchoolName {
            get {
                return ((string)(this["SchoolName"]));
            }
            set {
                this["SchoolName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1019999")]
        public int TenantId {
            get {
                return ((int)(this["TenantId"]));
            }
            set {
                this["TenantId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lab-two.sims8.com/")]
        public string LabTwoURL {
            get {
                return ((string)(this["LabTwoURL"]));
            }
            set {
                this["LabTwoURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=lab-two.sims8.com;Initial Catalog=SIMS8_Farm1_Business_A;User ID=sa;P" +
            "assword=Pa$$w0rd")]
        public string LabTwoDatabaseConnectionString {
            get {
                return ((string)(this["LabTwoDatabaseConnectionString"]));
            }
            set {
                this["LabTwoDatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C2K")]
        public string EnterpriseName {
            get {
                return ((string)(this["EnterpriseName"]));
            }
            set {
                this["EnterpriseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testuser@capita.co.uk")]
        public string EnterpriseUser {
            get {
                return ((string)(this["EnterpriseUser"]));
            }
            set {
                this["EnterpriseUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pa$$w0rd")]
        public string EnterprisePassword {
            get {
                return ((string)(this["EnterprisePassword"]));
            }
            set {
                this["EnterprisePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lab-two.sims8.com/")]
        public string URL {
            get {
                return ((string)(this["URL"]));
            }
            set {
                this["URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Local")]
        public string MethodOfExecution {
            get {
                return ((string)(this["MethodOfExecution"]));
            }
            set {
                this["MethodOfExecution"] = value;
            }
        }
    }
}
